export const AUTH_TOKEN_COOKIE_NAME = "auth_token";
export const SHOPPER_AUTH_TOKEN_NAME = "shopper_token";
export const ONE_YEAR_AS_MS = 31536000000;
export const SHOPPER_NOT_FOUND_IN_DATABASE = "SHOPPER_NOT_FOUND_IN_DATABASE";
export const SAVED_CARD_NOT_FOUND_IN_USER = "SAVED_CARD_NOT_FOUND_IN_USER";

export const UPLOAD_LIMIT = 15000000;
export const DEFAULT_IMAGE_UPLOAD_TYPE = "jpeg";
export const FILE_UPLOAD_NAME_CHARACTER_LIMIT = 20;
export const DEFAULT_IMAGE_EXTENSION = `.${DEFAULT_IMAGE_UPLOAD_TYPE}`;
export const DEFAULT_IMAGE_UPLOAD_MIME_TYPE = `image/${DEFAULT_IMAGE_UPLOAD_TYPE}`;
